---
- hosts: jenkins-slave
  become: true 
  tasks: 
    - name: update ubuntu repo and cache 
      apt: 
        update_cache: yes 
        force_apt_get: yes  # Corrected typo here
        cache_valid_time: 3600 

    - name: install java 
      apt: 
        name: openjdk-11-jre
        state: present

    - name: download maven packages 
      get_url:
        url:  https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        dest: /opt/apache-maven-3.9.6-bin.tar.gz  # Specify the full path including the file name

    - name: extract maven packages 
      unarchive:
        src: /opt/apache-maven-3.9.-bin.tar.gz
        dest: /opt/maven  # Extract to a specific directory to avoid potential issues
        remote_src: yes
        creates: /opt/maven/apache-maven-3.9.6  # Prevents re-extraction if already extracted
